### ISSUE TITLE
'Charged end of' instead of 'Charged on'

### ISSUE THREAD

**Issue by HenrikBengtsson** [poundifdef/VirginMobileMinutesChecker#18]
ISSUE:
At the end of each billing cycle, I can never remember at what hour of the 'Charged on' date my minutes runs out.  For instance, on April 10, I will ask myself if 'Charged on: 04/11/12' means that I will get fresh minutes on April 11 @ 00:01 or on April 11 @ 23:59.  It turns out to be the latter.

SOLUTION:
Relabeling 'Charged on' to 'Charged end of' will remove this ambiguity.

Thanks,

Henrik

**Comment by gurchik** [comment]
The "Charged on" wording refers to the last day of your billing cycle (i.e., when Virgin Mobile will charge your account and give you new minutes). To be honest, I've always believed that accounts are charged on a random time sometime after noon on the last day of your billing cycle.

For example, if I added money to my account on April 1st, the Virgin Mobile Minutes Checker will report that my account is "Charged on" May 1st. That means that, come May 1st, Virgin Mobile will charge money to my account on a random time during May 1st (usually around 7-10pm), and once paid, I will be given new minutes and the Checker will now report that the new "Charged on" date is June 1st.

I've never thought too hard on the wording of this, and I thought it was pretty explainatory on its own, but maybe instead of changing it to "Charged end of," maybe it should instead point out that the date refers to the last day of the billing day. Maybe display "Billing Cycle: April 1st - May 1st" or just "End of Billing Cycle: May 1st."

Changing it to "Expiry date" might also work, but that might be ambiguous (if you have $200 in your account, you might think "Expiry date" means when your money is completely used, not when it's next charged.)

I'd suggest closing this "WONTFIX".

**Comment by HenrikBengtsson** [comment]
OK, so my bad for assuming everyone else are also billed at 11:59pm local timezone.

I do like your proposal of "End of Billing Cycle" or maybe better "Last Day of Billing Cycle".

I see the problem of having a too long label.

Using "Billing Cycle: April 1st - May 1st" is a bit confusing, e.g.

Previous Billing Cycle: March 1st - April 1st
Billing Cycle: April 1st - May 1st
Next Billing Cycle: May 1st - June 1st

Your call.

**Comment by gurchik** [comment]
Virgin Mobile in AU calls the last day of a billing cycle the "[Billing Cycle Date](http://virginmobile.custhelp.com/app/answers/detail/a_id/458/~/billing-cycles)." However (I didn't know this until now because you are not able to access your Account page if your bill has not been paid; pretty absurd) Virgin Mobile themselves call the last day of the billing cycle the day "[you will be charged on](http://i54.tinypic.com/2utg4sg.jpg)." 

I think its more appropriate to stay with the terminology Virgin Mobile use themselves on their website, so I again suggest this issue be closed; however, it's ultimately up to @poundifdef.

**Comment by poundifdef** [comment]
Interestingly, VM changes the wording on their website every so often, and it might even be different for PayLo vs BeyondTalk plans (this app is built for BeyondTalk, but people still use it for paylo.)

I'm willing to change this to something more intuitive, even if it does not match VM's website, as long as it's accurate. I am not sure if there is continuity for when exactly those changes go through. I doubt that /everybody/ is charged at the same time - I imagine the cronjob or notification system spans several hours.

I get a txt message when my account is renewed; if you have a text message history of the exact times you are renewed, we may be able to find a pattern?

**Comment by HenrikBengtsson** [comment]
The regular Messaging app on Android 2.2.1 does not show timestamps (only dates), so I used the 'SMS to Text' (by SMeiTi) to filter and dump SMS message (from 0000000868) to a text file on the SD card.  This reveals that all of those notices read:

  "New Month at Midnight! You get Mins: 300 Anytime Msgs: Unlim Data: Unlim All for $$25"

Note that they explicitly say "at Midnight".  BTW, I'm on a "Beyond Talk" plan.

FYI, I've received those messages at different times during the day, but mostly commonly around 8-9pm (I think the timezone is local time, which for me is PDT), e.g.

2011-10-03 00:09:30
2011-11-03 21:13:42
2011-12-03 21:03:47
2012-02-03 20:29:29
2012-03-03 20:24:59
2012-04-03 20:25:30

**Comment by gurchik** [comment]
I asked Virgin Mobile about this and this is what they had to say:

> Should the customer be on a monthly plan, the Current Through Date (CTD)
> is when their minutes for the current month are good through. [...]
> 
> On the current through date the monthly charge will be charged around 8
> PM local time.
> We will attempt to sweep the cash balance first, if there's not enough
> and it's not successful, we will attempt a registered payment type
> (credit/debit card or PayPal account) if there is one.

**Comment by HenrikBengtsson** [comment]
Not sure what your question to them was, but they don't really say at what time (hour and minute) the new billing period _starts_, only _when they charge_ for it.  I don't think that's the same.  But they gave yet another alternative what to call the last day of billing cycle - "Through Date".

**Comment by gurchik** [comment]
Ah yes, I'm sorry that I left that out, I thought the only relevant part was when they charge for it. Basically, they said that the new billing cycle starts at midnight, but it's charged around 8 and if you don't have the sufficient funds at that time, your account will be terminated. This was the only relevant part for me, since I rarely have money in my account and I was trying to predict the time I actually lose service (now I know it's around 8pm), so forgive me for leaving that part out.

Just to repeat: your account is billed around 8pm, and if you don't have enough funds, you lose service. If the payment was successful, the next month starts on midnight.
